mongo:
  image: mongo:3.0.4
  ports:
    - "27017:27017"
  volumes:
    - './data:/data/db'
api:
  build: .
  command:  bash -c "npm install; nodemon app.js --color=always"
  ports:
    - "8081:8081"
    - "5859:5859"
  volumes:
    - ./app:/usr/src/app
  links:
    - mongo
